<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEpUEmGb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEpUEmGb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEpUEmGb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEpUEmGb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEpUEmGb\App_KernelDevDebugContainer([
    'container.build_hash' => 'EpUEmGb',
    'container.build_id' => 'd01f6d2f',
    'container.build_time' => 1603091078,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEpUEmGb');
